### PR TITLE
Sms snippets

### PR DESCRIPTION
**Pull request by jarodreyes**
Added snippets for a bunch of basic SMS activities.

### CODE REVIEW

**Comment by jarodreyes** [comment]
Well it certainly seems like copy/paste from the quickstarts is not going to work... boo. Will take a look at writing from scratch this weekend.

**Comment by mcelicalderon** [comment]
@jarodreyes Just FWI build is failing because of the TwiML snippets. Testing is not currently supported for snippets that use and run a web framework like Flask and Sinatra as an actual request would have to be made to the server that runs upon snippet execution. But you can mark a snippet not to be tested in the meta.json file or a whole directory by adding a `test.yml` file whose content is `testable: false`. Also, there might be a better place for TwiML snippets as they are not actual `rest/` snippets. Maybe something similar to what we have in the `voice/` dir would be a better approach.

**Comment by jarodreyes** [comment]
@mcelicalderon Ready for you bud! Just need the latest php 5.x snippets.

**Comment by mcelicalderon** [comment]
Great, I'll create those later today 👍

**Comment by mcelicalderon** [comment]
@jarodreyes done. Just one thing. A snippet to send sms already exists [here](https://github.com/TwilioDevEd/api-snippets/tree/master/rest/messages/send-message). The one you are creating `send-sms` is almost the same. The only difference is that in the new one you don't provide a media url for the created sms.

**Comment by jarodreyes** [comment]
@mcelicalderon Correct we need a basic SMS example without mediaUrl.

**Comment by mcelicalderon** [comment]
Ok then, merging as soon as the build passes. 👍

**Pull request merged**
