### PR TITLE
Wireless binary commands

### PR DESCRIPTION
**Pull request by jonedavis**

### CODE REVIEW

**Comment by atbaker** [comment]
@smendes / @joliveros / @hortega / @well1791 - Can you update me on the state of these Travis builds? Do we expect them to pass for all PRs these days or is there something wrong with the builds which will always cause them to fail?

It's okay if our CI needs some work - I just want to know if it's safe to merge @jonedavis's PR.

**Comment by atbaker** [comment]
@smendes @joliveros @hortega @well1791 Disregard! @dprothero brought me up to speed

**Comment by dprothero** [comment]
Actually, @smendes / @joliveros / @hortega / @well1791 I think I am going to need your help! I'll open a ticket.

**Comment by well1791** [comment]
Hi @jonedavis, @dprothero 

I think this PR is almost done ^^, thanks to this PR I also updated [TwilioDevEd/twilio-api-faker](https://github.com/TwilioDevEd/twilio-api-faker). Please let me know if I can help you with any other bug.

**Comment by jonedavis** [comment]
@well1791 You're awesome 😀

**Comment by jonedavis** [comment]
Hey @well1791 

Restoring this branch. Looks like the Commands (text and binary) snippets are invalid. Can you take another pass at it?

For both Binary and Text:

- C# doesn't include a destination SIM
- Java doesn't include a destination SIM
- Node doesn't include a destination SIM

Php is wrong, which makes me wonder if the other helper libraries follow a similar syntax?
It should be:

```
$client->wireless
    ->commands
    ->create("wakeup",
    [
      "sid" => "AliceSmithSmartMeter",
    ]);
```

Note where the actual command is sent (in a param of its own not in array)


- Remove callbackUrl from all language (and curl) examples



Thanks!

**Comment by well1791** [comment]
Got it, I'll take care of it.

But, regarding the `sim` feature in node, java and csharp:
I think they are already implemented, see: [twilio-node](https://github.com/twilio/twilio-node/blob/master/lib/rest/wireless/v1/command.js#L335), [twilio-java](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/rest/wireless/v1/CommandCreator.java#L50) and [twilio-csharp](https://github.com/twilio/twilio-csharp/blob/master/src/Twilio/Rest/Wireless/V1/CommandResource.cs#L314)

**Comment by well1791** [comment]
@jonedavis this is the PR: https://github.com/TwilioDevEd/api-snippets/pull/472

**Comment by jonedavis** [comment]
Looks good, thanks @well1791

**Pull request merged**
