### PR TITLE
Adds url encoding to Notify Create Binding curl example

### PR DESCRIPTION
**Pull request by viktormuller**
Many fields in Create Binding request supports unicode and hence need to be url encoded.

### CODE REVIEW

**Comment by viktormuller** [comment]
Hey @atbaker, added url encoding to critical curl examples where it could easily cause problems (e.g. phone numbers, credential secrets, some identity / friendly name)

**Comment by atbaker** [comment]
@viktormuller We should only need the `--data-urlencode` on the GET code samples, right?

Looking at the man page, `-d` form encodes payloads in the request body for POST requests. `--data-urlencode` adds payloads to the request URL and encodes them appropriately:

https://curl.haxx.se/docs/manpage.html#-d

**Comment by viktormuller** [comment]
@atbaker Actually no. I am pretty sure it is very needed on POST requests, you can test by trying the following: 

curl -XPOST https://notify.twilio.com/v1/Services/ISXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Bindings \
    -d "Identity=00000001" \
    -d "BindingType=sms" \
    -d "Address=+18571234567" \
    -u 'your_account_sid:your_auth_token'
    --trace-ascii

You will see how the "+" char is not urlencoded and it is interpreted as  " " (space). This is actually the issue a customer just ran into.

**Comment by atbaker** [comment]
@viktormuller Ah, right. I always forget about the `+` values specifically.

Merged!

**Pull request merged**
