### PR TITLE
Update chat 7.x java code snippts

### PR DESCRIPTION
**Pull request by teoreteetik**

### CODE REVIEW

**Comment by teoreteetik** [comment]
@carlsolivier

**Comment by dprothero** [comment]
@teoreteetik Can you revert these changes:
image

The way that it was is the standard for the docs website (for consistency and so our search/replace works for the logged in user's credentials).

Thanks!

**Comment by teoreteetik** [comment]
Most of the snippets have `ACCOUNT_SID` and `AUTH_TOKEN` so I changed these for consistency. 
I'll change these back, but should I change the `ACCOUNT_SID` and `AUTH_TOKEN` to `ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` and `your_auth_token` in _all_ java 7.x Chat snippets?

**Comment by dprothero** [comment]
If it's not to much trouble, that would be awesome. If not, just let me know and we'll make a pass through to globally search/replace.

**Comment by teoreteetik** [comment]
Fixed, @dprothero

**Comment by dprothero** [comment]
thanks @teoreteetik! LGTM

**Pull request merged**
