### PR TITLE
Add rubocop for ruby snippets

### PR DESCRIPTION
**Pull request by joliveros**

### CODE REVIEW

**Comment by joliveros** [comment]
@juancarlospaco Would you mind reviewing this?

**Comment by juancarlospaco** [comment]
- Adding Rubocop for ruby snippets looks good to me. :+1: :shipit:
- C.I. Linters complain because line lenght is > 80 chars, minor.

**Comment by acamino** [comment]
@joliveros what do you think about closing this pull request? I'm pretty sure we can figure out how to include a lintern very soon. Our priority now is to finish with the Ruby snippets.

**Comment by joliveros** [comment]
Sure, let's put it on hold

**Pull request closed without merging**
