### PR TITLE
Replace mustache placeholders

### PR DESCRIPTION
**Pull request by mcelicalderon**
For snippet testing to work, user data placeholders should use a format that resembles the original value. 

```
Account SID: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Call SID: CAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

### CODE REVIEW

**Comment by mcelicalderon** [comment]
@kwhinnery @jarodreyes @dprothero @atbaker Do you think we should follow some guidelines for code snippets, like the one I specified in this PR's readme file?

In this PR I just replaced every `{{ account_sid }}` with `ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

Please let me know what you think.

**Comment by dprothero** [comment]
I think the idea behind the mustache placeholders was so we could eventually dynamically replace them with the logged-in user's credentials. However, as long as we use a consistent value -- and it's not a value likely to occur in any other context -- then I think we should be fine.

**Comment by mcelicalderon** [comment]
@dprothero Yes, consistency is the most important factor here. In the past we did had a conversation about using mustache or a format that resembles the actual value. In the end, we decided to go with the second option. But, if anyone thinks mustache is better for any reason I can adapt to that, I just need to make it consistent.

**Comment by mcelicalderon** [comment]
I will merge this as we can change it later if that decision was to be made. For now, we will have consistency as many placeholders already use the `ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` format.

**Pull request merged**
